-- For inserting single value
INSERT INTO STUDENT (ID,NAME,ADDRESS)
VALUES (1,'PRIT CHAVDA','AHMEDABAD');

-- For inserting multiple values
INSERT INTO STUDENT (ID,NAME,ADDRESS)
VALUES (1,'PRIT CHAVDA','AHMEDABAD'),
(1,'PRATHAM DOSHI','VASDA'),
(2,'TEJAS RAVAL','BHILODA'),
(3,'RONAK DUBE','VAPI'),
(4,'SHWBHAGYA','JAMNAGAR'),;